trigger:
- test-azure

jobs:
  - job: Linux_Build
    variables:
      conda_version: 'MacOSX-x86_64'
      conda_root: '$(Agent.HomeDirectory)/miniconda3'
      vcpkg_root: '$(Agent.HomeDirectory)/vcpkg'
      python_arch: 'x64'
      triplet: 'x64-linux'
    strategy:
      matrix:
        # linux_python_27:
        #   image_name: 'ubuntu-16.04'
        #   python_version: 2.7
        #   python_arch: 'x64'
        #   conda_version: 'Linux-x86_64'
        #   triplet: 'x64-linux'
        # linux_python_35:
        #   image_name: 'ubuntu-16.04'
        #   python_version: 3.5
        #   python_arch: 'x64'
        #   conda_version: 'Linux-x86_64'
        #   triplet: 'x64-linux'
        linux_python_36:
          python_version: 3.6
          conda_version: 'Linux-x86_64'
        # linux_python_37:
        #   image_name: 'ubuntu-16.04'
        #   python_version: 3.7
        #   python_arch: 'x64'
        #   conda_version: 'Linux-x86_64'
        #   triplet: 'x64-linux'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install ninja-build swig libudev-dev
      displayName: 'Install toolchain'
    - script: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$(conda_version).sh -O $(Agent.HomeDirectory)/miniconda.sh
        bash $(Agent.HomeDirectory)/miniconda.sh -b -p $(conda_root)
      displayName: 'Install conda'
    - script: |
        $(conda_root)/bin/conda create -yq -n python$(python_version) python=$(python_version)
      displayName: 'Install Python $(python_version)'
    - script: |
        git clone https://github.com/NordicPlayground/vcpkg.git $(vcpkg_root)
        $(vcpkg_root)/bootstrap-vcpkg.sh
      displayName: 'Install vcpkg'
    - script: |
        export PATH=$VCPKG_ROOT:$PATH
        vcpkg install nrf-ble-driver:$(triplet)
      env: {
        VCPKG_ROOT: '$(vcpkg_root)',
      }
      displayName: 'Install nrf-ble-driver'
    - script: |
        export PATH=$(conda_root)/envs/python$(python_version)/bin:$PATH
        pip install -r requirements-dev.txt
        python setup.py bdist_wheel --build-type Debug
      env: {
        VCPKG_ROOT: '$(vcpkg_root)',
      }
      displayName: 'Build'

  # macOS
  - job: macOS_Build
    variables:
      conda_version: 'MacOSX-x86_64'
      conda_root: '$(Agent.HomeDirectory)/miniconda3'
      vcpkg_root: '$(Agent.HomeDirectory)/vcpkg'
    strategy:
      matrix:
        mac_python_36:
          python_version: 3.6
          python_arch: 'x64'
          triplet: 'x64-osx'
    pool:
      vmImage: 'macos-10.13'
    steps:
    - script: |
        ls /Applications
        sudo xcode-select -s /Applications/Xcode_10.1.app
      displayName: 'Install toolchain'
    - script: |
        brew install gcc swig
      displayName: 'Install toolchain'
    - script: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$(conda_version).sh -O $(Agent.HomeDirectory)/miniconda.sh
        bash $(Agent.HomeDirectory)/miniconda.sh -b -p $(conda_root)
      displayName: 'Install conda'
    - script: |
        $(conda_root)/bin/conda create -yq -n python$(python_version) python=$(python_version)
      displayName: 'Install Python $(python_version)'
    - script: |
        git clone https://github.com/NordicPlayground/vcpkg.git $(vcpkg_root)
        $(vcpkg_root)/bootstrap-vcpkg.sh
      displayName: 'Install vcpkg'
    - script: |
        export PATH=$VCPKG_ROOT:$PATH
        vcpkg install nrf-ble-driver:$(triplet)
      env: {
        VCPKG_ROOT: '$(Agent.HomeDirectory)/vcpkg',
      }
      displayName: 'Install nrf-ble-driver'
    - script: |
        export MACOSX_DEPLOYMENT_TARGET=10.10
        export PATH=$(conda_root)/envs/python$(python_version)/bin:$PATH
        export PYTHON_VERSION=$(python_version)
        pip install -r requirements-dev.txt
        python setup.py bdist_wheel --build-type Debug -- -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12
      env: {
        VCPKG_ROOT: '$(Agent.HomeDirectory)/vcpkg',
      }
      displayName: 'Build'

  # Windows
  - job: Windows_Build
    variables:
      conda_root: '$(Agent.HomeDirectory)\miniconda3'
      vcpkg_root: '$(Agent.HomeDirectory)\vcpkg'
    strategy:
      matrix:
        win64_python_36:
          python_version: 3.6
          python_arch: 'x64'
          triplet: 'x64-windows'
        win32_python_36:
          python_version: 3.6
          python_arch: 'x86'
          triplet: 'x86-windows'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    # - script: |
    #     choco install -y --x86 swig
    #     choco install -y --x86 ninja
    #     choco install -y miniconda3 --params="'/D:$(conda_root)'"
    #   condition: eq(variables['python_arch'], 'x86')
    #   displayName: 'Install toolchain on Windows'
    - script: |
        choco install -y --x86 swig
        choco install -y ninja
        choco install -y miniconda3 --params="'/D:$(conda_root)'"
      # condition: eq(variables['python_arch'], 'x64')
      displayName: 'Install toolchain on Windows'
    - script: |
        $(conda_root)\Scripts\conda create -yq -n python$(python_version) python=$(python_version)
      condition: eq(variables['python_arch'], 'x64')
      displayName: 'Install Python $(python_version)'
    - script: |
        call set CONDA_FORCE_32BIT=1
        $(conda_root)\Scripts\conda create -yq -n python$(python_version) python=$(python_version)
      condition: eq(variables['python_arch'], 'x86')
      displayName: 'Install Python $(python_version)'
    - script: |
        git clone https://github.com/NordicPlayground/vcpkg.git $(vcpkg_root)
        $(vcpkg_root)\bootstrap-vcpkg.bat
      displayName: 'Install vcpkg'
    - script: |
        set PATH=$(vcpkg_root);%PATH%
        vcpkg install nrf-ble-driver:$(triplet)
      env: {
        VCPKG_ROOT: '$(vcpkg_root)',
      }
      displayName: 'Install nrf-ble-driver'
    - script: |
        call $(conda_root)\Scripts\activate python$(python_version)
        pip install -r requirements-dev.txt
        python setup.py bdist_wheel --build-type Debug
      env: {
        VCPKG_ROOT: '$(vcpkg_root)',
      }
      condition: eq(variables['python_arch'], 'x64')
      displayName: 'Build'
    - script: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\tools\vsdevcmd.bat" -vcvars_ver=14.0  -arch=x86
        call set CONDA_FORCE_32BIT=1
        call $(conda_root)\Scripts\activate python$(python_version)
        call set
        python --version
        python version.py
        pip install -r requirements-dev.txt
        python setup.py bdist_wheel --build-type Debug
      env: {
        VCPKG_ROOT: '$(vcpkg_root)',
      }
      condition: eq(variables['python_arch'], 'x86')
      displayName: 'Build'



    # # Install nrf-ble-driver
    # - script: |
    #     git clone https://github.com/NordicPlayground/vcpkg.git $(Agent.HomeDirectory)/vcpkg
    #     $(Agent.HomeDirectory)/vcpkg/bootstrap-vcpkg.sh
    #   condition: not(contains(variables['image_name'], 'win'))
    #   displayName: 'Install nrf-ble-driver for Linux or macOS'
    # - script: |
    #     export PATH=$VCPKG_ROOT:$PATH
    #     echo $PATH
    #     echo $VCPKG_ROOT
    #     vcpkg install nrf-ble-driver:$(triplet)
    #   condition: not(contains(variables['image_name'], 'win'))
    #   env: {
    #     VCPKG_ROOT: '$(Agent.HomeDirectory)/vcpkg',
    #   }
    #   displayName: 'Install nrf-ble-driver for Linux or macOS'
    # - script: |
    #     git clone https://github.com/NordicPlayground/vcpkg.git $(Agent.HomeDirectory)/vcpkg
    #     $(Agent.HomeDirectory)\vcpkg\bootstrap-vcpkg.bat
    #   condition: contains(variables['image_name'], 'win')
    #   env: {
    #     VCPKG_ROOT: '$(Agent.HomeDirectory)\vcpkg',
    #   }
    #   displayName: 'Install nrf-ble-driver for Windows'
    # - script: |
    #     set PATH=%VCPKG_ROOT%;%PATH%
    #     echo %PATH%
    #     echo %VCPKG_ROOT%
    #     vcpkg install nrf-ble-driver:$(triplet)
    #   condition: contains(variables['image_name'], 'win')
    #   env: {
    #     VCPKG_ROOT: '$(Agent.HomeDirectory)\vcpkg',
    #   }
    #   displayName: 'Install nrf-ble-driver for Windows'

    # Build
    # - script: |
    #     export PATH=$VCPKG_ROOT:$PATH
    #     echo $PATH
    #     echo $VCPKG_ROOT
    #     vcpkg list
    #     python -V
    #     p_v=`which python`
    #     p_d=`dirname $p_v`
    #     echo ls p_d
    #     ls $p_d
    #     echo ls p_d/bin
    #     ls $p_d/bin
    #     python-config --includes
    #     pip install -r requirements-dev.txt
    #     python setup.py bdist_wheel --build-type Debug
    #   env: {
    #     VCPKG_ROOT: '$(Agent.HomeDirectory)/vcpkg',
    #   }
    #   condition: contains(variables['image_name'], 'ubuntu')
    #   displayName: 'Build'
    # - script: |
    #     export PATH=$VCPKG_ROOT:$PATH
    #     echo $PATH
    #     echo $VCPKG_ROOT
    #     vcpkg list
    #     python -V
    #     pip install -r requirements-dev.txt
    #     python setup.py bdist_wheel --build-type Debug
    #   env: {
    #     VCPKG_ROOT: '$(Agent.HomeDirectory)/vcpkg',
    #   }
    #   condition: contains(variables['image_name'], 'mac')
    #   displayName: 'Build'
    # - script: |
    #     set PATH=%VCPKG_ROOT%;%PATH%
    #     echo %PATH%
    #     echo %VCPKG_ROOT%
    #     vcpkg list
    #     python -V
    #     pip install -r requirements-dev.txt
    #     python setup.py bdist_wheel --build-type Debug
    #   env: {
    #     VCPKG_ROOT: '$(Agent.HomeDirectory)\vcpkg',
    #   }
    #   condition: contains(variables['image_name'], 'win')
    #   displayName: 'Build'
    # - bash: |
    #     cp -R build/stage/**/*.tar.gz "$(Build.ArtifactStagingDirectory)"
    #   displayName: 'Copy artifacts'
    # - task: GitHubRelease@0
    #   inputs:
    #     gitHubConnection: 'waylandCI'
    #     repositoryName: 'NordicSemiconductor/pc-nrfjprog-js'
    #     action: 'edit'
    #     tagSource: 'Git tag'
    #     tag: '$(Build.SourceBranchName)'
    #     assetUploadMode: 'replace'
    #     isDraft: 'true'
    #     addChangeLog: 'false'
    #   condition: ne(variables['Build.Reason'], 'PullRequest')

  # - job: Test
  #   dependsOn: [
  #     Build,
  #   ]
  #   strategy:
  #     matrix:
  #       linux:
  #         osType: 'linux'
  #       mac:
  #         osType: 'mac'
  #       win64:
  #         osType: 'win64'
  #       win32:
  #         osType: 'win32'
  #   pool: server
  #   steps:
  #   - task: InvokeRESTAPI@1
  #     displayName: Test
  #     inputs:
  #       connectionType: 'connectedServiceName'
  #       serviceConnection: 'waylandJenkins'
  #       method: 'POST'
  #       urlSuffix: 'view/pc-nrfjprog-js/job/pc-nrfjprog-js-$(osType)/buildWithParameters?BRANCH=$(Build.SourceBranch)&VSTS_URL=$(system.CollectionUri)&TOKEN=$(system.AccessToken)&PROJECT_ID=$(system.teamProjectId)&HUB_NAME=$(system.hostType)&PLAN_ID=$(system.planId)&TASK_ID=$(system.taskInstanceId)&JOB_ID=$(system.jobId)'
  #       waitForCompletion: 'true'
  #     condition: ne(variables['Build.Reason'], 'PullRequest')
